### ISSUE TITLE
Multi-part country code [e.g. US-New_York] causes download and processing problems

### ISSUE THREAD

**Issue by apoorvalal** [datasciencecampus/mobility-report-data-extractor#11]
**Describe the bug**
I'm trying to download the SVGs for the reports for US states, and noticed that the `svg` command
produces duplicate countrycodes for states with multi-part names. Example below:

**To Reproduce**
1. `./mobius.py svg`

Produces 
```
153. US-New               (SVG/2020-03-29_US-New_Hampshire_Mobility_Report_en.svg)
154. US-New               (SVG/2020-03-29_US-New_Jersey_Mobility_Report_en.svg)
155. US-New               (SVG/2020-03-29_US-New_Mexico_Mobility_Report_en.svg)
156. US-New               (SVG/2020-03-29_US-New_York_Mobility_Report_en.svg)
157. US-North             (SVG/2020-03-29_US-North_Carolina_Mobility_Report_en.svg)
158. US-North             (SVG/2020-03-29_US-North_Dakota_Mobility_Report_en.svg)
```
2. Tried to download using correct fullname `US-New_York`. This downloads the correct files but and writes into a file `svgs/US-New.svg`, which gets overwritten by when i call `./mobius.py download US-New_Jersey` and so on. 

**Expected behavior**
Separate `countrycode` for each state even if the first word in the name is identical. 

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Python 3.7

**Comment by mshodge** [comment]
Thanks @apoorvalal we will fix as soon as possible. 

For now if you have an immediate need for one of the SVGs please manually download from:

https://console.cloud.google.com/storage/browser/mobility-reports/SVG

**Comment by mshodge** [comment]
@apoorvalal all fixed. Thanks for flagging.

**Comment by apoorvalal** [comment]
np; Thanks for the quick fix and the clean implementation of the extractor [I'd gotten as far as getting the text for each figure, but the PDF > SVG conversion to read the series is genius]. 
Hope to put the data to good use, and will cite when i do.

**Comment by mshodge** [comment]
Thanks @apoorvalal really appreciate the kind words. The team have moved onto other work now - fast pace timelines at the moment as I'm sure you'll understand - but will keep an eye on this repo if you have any questions. Thanks again. Michael
