### ISSUE TITLE
Script or function to generate mapping between graph_num and name?

### ISSUE THREAD

**Issue by jwhendy** [datasciencecampus/mobility-report-data-extractor#13]
**Is your feature request related to a problem? Please describe.**
I'm generating all the US data, including by state. This yield `./output/US-*/csv/i.csv`. It would be great to easily map `i` (counties for `US-foo`) to the associated name.

**Describe the solution you'd like**
Perhaps something like `python ./mobius.py proc -names input folder` which would title the files by the area name. Or simply `python ./mobius.py map input` which would generate a dict or json file with `i: area_name` for each graph.

**Describe alternatives you've considered**
 I'm currently brute forcing this by using  `download -p` followed by the linux command `pdftotext` and then processing the test file.

Other than the first page (which I ignore by skipping lines), all the other area names appear on the line before each instance of `Retail & recreation`. I iterate through `readlines()` using `enumerate`), then if I get a hit with`re.findall`, I know `lines[i-1]` is the area name. Since they're in order, each list index `i` corresponds to `i+1.csv`

Apologies if this already exists and I'm just missing it. I'm not sure how others are post-processing all the `i.csv` files that get generated?

**Comment by mshodge** [comment]
Hi @jwhendy we pushed a new function today called `mobius.py full`. Have a look and see if that matches what you're after.

**Comment by mshodge** [comment]
You'll need to download the PDFs too. 

So `mobius.py download CC -p`

Then `mobius.py full path/to/pdf path/to/svg path/to/output`

**Comment by jwhendy** [comment]
This is very cool and you're cranking out the features! in record time

I went with my own concocted solution, mostly because it was faster. I doubt you'd want to implement it (hacky and relies on the pdf text not changing). I didn't dig into the guts of pdfminer or how you're finding all the elements systematically vs. what I'm doing (keying off of form feed symbols indicating a new page).

For comparison, here was the output on just one state, `US-Alabama` (reported 27sec):
```
$ python ./mobius.py full pdfs/US-Alabama.pdf svgs/US-Alabama.svg ./output/
Extracting plot summaries: 408it [00:27, 14.63it/s]
Extracting data from SVG plots: 100%|█████████████████| 408/408 [00:01<00:00, 333.59it/s]
Plots with data: 280
```

With all the reports already downloaded (with `-p`) and everything processed to `./output`, [my code](https://gist.github.com/jwhendy/d28f17fd1837c1a3679768244969ef2b) runs through all 50 sates in ~9sec. I haven't fully debugged, but my spot checking has shown reasonable results so far.

**Comment by mshodge** [comment]
Great stuff @jwhendy if you ever think it should be implemented to this code then please feel free to make a pull request. The team have moved onto other work now - fast pace timelines at the moment as I'm sure you'll understand - so we are reliant on collaborators to improve our process. Thanks again. Michael

**Comment by ladew222** [comment]
I would like this feature as well. Another project has some relevant code as well https://github.com/kylemcdonald/covid-mobility-data.

**Comment by jwhendy** [comment]
@mshodge I would be honored to contribute, but realistically would probably be best fit to work with someone on that. I admit whenever I see a project with decorators I expect my skills have been surpassed :) 

I can take a look at understanding your code a bit better to see if I can make mine fit this style/structure better if this is of value. Let me know what you think.

**Comment by mshodge** [comment]
Hi both @jwhendy and @ladew222 our latest changes have made great improvements to the code - we think.

**Comment by ladew222** [comment]
Great. My goal it merge the data into my COVID Dataiewer I am build for USA that bring in social/census data. Right now I use https://github.com/ActiveConclusion/COVID19_mobility <https://github.com/ActiveConclusion/COVID19_mobility> which has the number but not the time series.

**Comment by jwhendy** [comment]
As an alternative approach, my script outputs the path to the associated .csv. Would it help to just post that? Once one has this, as long as `./output/US-foo/` has been generated with `proc`, one could merge them all together.

Alternatively, one could just do this and provide the csv directly for the US. I like the downloading-on-the-fly approach here *if the data updates*, but otherwise... it seems pretty redundant for local computers to all complete this tedious pdf/svg -> csv step, particularly if we're only going to see the data update every few days (or maybe it's frozen at 3/29 at this point).

**Comment by jwhendy** [comment]
I posted this in the linked issue, but circling back here in case a direct download of all the US county time series data is of interest.
---
For anyone tracking this down and just wanting all the data, I uploaded to my [covid19 exploration repo](https://github.com/jwhendy/covid19/tree/master/data).

- mobility-data-agg: the high level value pulled from the pdf for each state/county; note that this also contains the state-level averages (`df.county=='summary'`) and the states themselves (`df.area=='United States'`) so there's redundancy in that set
- mobilty-data-ts: time series data for each county. this *does not* have the US country data (country total, per-state levels) or the high level state summaries from pg1-pg2 of each PDF. It *only* has county level data.

![mobility-by-segment](https://user-images.githubusercontent.com/379357/78825650-f5e1c480-79a5-11ea-94af-aaa508016720.png)

Let me know if you find any errors. Currently not verified, but the plots are cool :) Look at the dual modes of residential and workplace, which might indicate those are the most robust indicators of what people are doing?

**Comment by ladew222** [comment]
Great. Thanks @mshodge.  I will take a look.

**Comment by mshodge** [comment]
Thanks @jwhendy I will create a section in the readme for brilliant uses of the code like this. I will then link to your comment.

**Comment by ladew222** [comment]
Thanks as well @mshodge and @jwhendy.  My dashboard with is now at[ www.balefire.info ]( www.balefire.info)and is now fully integrated with the data from your tool.  It maps COVID-19 data, census information and Google information at county level and displays it on a choropleth. It also allows users to look at correlations between confirmed cases and these data points.  As it shows,  the Google data is strong.
