### ISSUE TITLE
New York data seems out of order in places

### ISSUE THREAD

**Issue by RobJY** [datasciencecampus/mobility-report-data-extractor#16]
**Describe the bug**
The output for New York state looks incorrect for plots/csv files 9-27 and 93.

**To Reproduce**
1. python ./mobius.py proc -p svgs/US-New_York.svg output

**Expected behavior**
I expected the plots/csv files to be in the same order as in the URL: https://www.gstatic.com/covid19/mobility/2020-03-29_US_New_York_Mobility_Report_en.pdf

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 80.0.3987.122

**Additional context**
The plots/csv files 9-17 just seem out of order.  Here's a mapping from current to correct order:  
* 9 -> 10
* 10 -> 11
* 11 -> 12
* 12 -> 13
* 13 -> 14
* 14 -> 15
* 15 -> 16
* 16 -> 17
* 17 -> 9
* 19 -> 27
* 20 -> 19
* 21 -> 20
* 22 -> 21
* 23 -> 22
* 24 -> 23
* 25 -> 24
* 26 -> 25
* 27 -> 26

Looking through a bit more I also found that 93 looks out of place.

**Comment by mshodge** [comment]
Hi there. We have noticed this for other countries too. I have created a patch, and am waiting on other project members to approve #17

**Comment by mshodge** [comment]
Hi @RobJY all resolved in the latest version of the code

**Comment by RobJY** [comment]
Great, thanks for the quick response!!

**Comment by mshodge** [comment]
No problem. Time is important for those who want to use the data. So we aim to resolve bugs as fast as we can.
