### ISSUE TITLE
Single points are not calculated (only segments)

### ISSUE THREAD

**Issue by mshodge** [datasciencecampus/mobility-report-data-extractor#2]
**Describe the bug**
If there is a point on the graph (i.e. a single days value) rather than a series of points (segment), this is not captured currently. This is problematic if the last point on the graph is a single data point (not part of a segment) as the headline figure in the PDF will be different.

**Comment by philip-lee-ons** [comment]
When saved with Affinity and loaded with svgpathtools, the single points are a closed Path with CubicBezier segments.

Two things likely to need changing:

1. Alter getgraphs.py to pick up the single points (may already come through, worth checking)
2. Handle the closed path used to represent the single points (e.g. find the centroid, add this into the trend line)
