### ISSUE TITLE
Update dates to April 9

### ISSUE THREAD

**Issue by jzamalloa1** [datasciencecampus/mobility-report-data-extractor#20]
This might be a simple request, but can you update the dates to the newest date (April 9)? Or, have a place where we can filter/modify it?

**Comment by mshodge** [comment]
Hi @jzamalloa1 I will update the pipeline and data today. Any particular region you'd like me to start with?

**Comment by mshodge** [comment]
Uploading now, should all be online in an hour max

**Comment by mshodge** [comment]
@jzamalloa1 all working now. Give it a whirl.

**Comment by jzamalloa1** [comment]
Works, thanks!
