### ISSUE TITLE
Certain country code downloads result in pdfs that are actually svgs

### ISSUE THREAD

**Issue by jwhendy** [datasciencecampus/mobility-report-data-extractor#22]
**Describe the bug**
It appears certain US-foo svgs are replicates of the svgs.

**To Reproduce**
```
$ git log
commit 28ddbb0a386d408e7c3a60e1959e1b91f94d8362
$ rm svgs/US-Alabama.svg 
$ rm pdfs/US-Alabama.pdf 
$ python ./mobius.py download US-Alabama

Download US-Alabama svg complete. Saved to /svgs
Download US-Alabama pdf complete. Saved to /pdfs
$ evince pdfs/US-Alabama.pdf
```
![grab_2020-04-10_133535](https://user-images.githubusercontent.com/379357/79014339-4d13a080-7b30-11ea-9032-6bec7438947d.png)

This works:
```
$ mv pdfs/US-Alabama.pdf pdfs/US-Alabama.svg
$ firefox pdfs/US-Alabama.svg
```

This also happens for US-Arizona. Haven't checked them all yet.

**Expected behavior**
svgs are svgs, pdfs are pdfs.

**Screenshots**
above

**Desktop (please complete the following information):**
arch linux, python 3.8

**Comment by jwhendy** [comment]
I created an `if` check for `US-Alabama` and `US-Arizona` and everything else ran so I believe it's just these two.

**Comment by mshodge** [comment]
Hi @jwhendy all should be fixed now. Seemed Alabama and Arizona's SVGs sneaked into the PDF  bucket.

**Comment by jwhendy** [comment]
Confirming fixed. Thanks for the fast response!
