### ISSUE TITLE
Date format change in most recent update

### ISSUE THREAD

**Issue by jwhendy** [datasciencecampus/mobility-report-data-extractor#24]
**Describe the bug**
Date format changed from `2020-03-29` to `2020-04-05`. Consistency is probably important and my personal opinion is the UTC format is less ambiguous and more universal (`%Y-%m-%d`

**To Reproduce**
```
$ cat mobility-report-data-extractor/config/dates_lookup_2020_03_29.csv 
index,date
1,2020-02-16
2,2020-02-17
3,2020-02-18
4,2020-02-19

$ cat mobility-report-data-extractor/config/dates_lookup_2020_04_05.csv 
index,date
1,23/02/2020
2,24/02/2020
3,25/02/2020
4,26/02/2020
```

**Comment by mshodge** [comment]
I'll update the file soon. Thanks for the spot.
