### ISSUE TITLE
Loop through states, create CSVs

### ISSUE THREAD

**Issue by dafriedman97** [datasciencecampus/mobility-report-data-extractor#26]
Thanks so much for creating this awesome tool! I was hoping to loop through the U.S. states and create a CSV for each. I'm new to working with bash so apologies if there's an obvious way to do this. Thanks so much!

**Comment by mshodge** [comment]
Hi @dafriedman97 line 23 will need changing from the run_all.sh file just to take the files with US- names. I'll try and get the change for you later today.

**Comment by mshodge** [comment]
Hi @dafriedman97 please find attached here a bespoke version of the bash file to run for all US states (doesn't include US main report).

Run using `bash run_US_states_sh`.

Let me know if you have any issues. This will run for both report dates, the original, and the latest.

[run_US_states.sh.zip](https://github.com/datasciencecampus/mobility-report-data-extractor/files/4464509/run_US_states.sh.zip)

**Comment by dafriedman97** [comment]
@mshodge Thanks so much! Any chance this will be added to the repository so we can pull directly? Thanks!

**Comment by mshodge** [comment]
Hi @dafriedman97 no problem. Just uploaded to the `master` branch.
