### ISSUE TITLE
Some SVGs are not available

### ISSUE THREAD

**Issue by mribeirodantas** [datasciencecampus/mobility-report-data-extractor#27]
**Describe the bug**
There are three SVG files missing and therefore three intervals that for three countries there is no data. Does anyone have the SVG files?

https://storage.cloud.google.com/mobility-reports/SVG/2020-03-29_AR_Mobility_Report_en.svg
https://storage.cloud.google.com/mobility-reports/SVG/2020-04-05_ZM_Mobility_Report_en.svg
https://storage.cloud.google.com/mobility-reports/SVG/2020-04-05_ZW_Mobility_Report_en.svg

**Comment by mshodge** [comment]
Apologies @mribeirodantas I will update these soon.

**Comment by mribeirodantas** [comment]
I appreciate the quick response, @mshodge! If it's possible also to explain how I could do it too, I think that would be great.

**Comment by mshodge** [comment]
All uploaded @mribeirodantas.

See [this section of the README](https://github.com/datasciencecampus/mobility-report-data-extractor#creating-your-own-svg) for instructions on how to create the SVGs. You'll need Affinity Designer I'm afraid.
