### ISSUE TITLE
Assuming single segment trend line, not yet handled

### ISSUE THREAD

**Issue by ladew222** [datasciencecampus/mobility-report-data-extractor#3]
I am getting this error on UK.svg.  I also noted that on my mac it was trying to read .dhstore files in the svg dir. I solved the second issue by  adding :

name, ext = os.path.splitext(file)
        if ext == '.svg':

in line 50 in createcsvs.py

**Comment by mshodge** [comment]
Thanks @ladew222 we will endeavour to fix this bug soon. We will also incorporate your dhstore flag. What version of MacOS are you using?

**Comment by ladew222** [comment]
Thanks. I am using Catalina

**Comment by mshodge** [comment]
@ladew222 thanks. This should have now been fixed in the latest version of the code. Please use `git pull`.
