### ISSUE TITLE
mobius.py bug

### ISSUE THREAD

**Issue by mrfox321** [datasciencecampus/mobility-report-data-extractor#30]
This function, in `mobius.py` has not been updated with the new `summarise` function signature, `doc, doc_files`.

    @cli.command(help="Produce summary CSV of regional headline figures from CSV")
    @click.argument("INPUT_PDF", type=click.Path(exists=True))
    @click.argument("OUTPUT_FOLDER")
    def summary(input_pdf, output_folder):

        with mobius.io.open_document(input_pdf) as doc:
            summary_df = mobius.extraction.summarise(doc)

        mobius.io.write_summary(summary_df, input_pdf, output_folder)

causing `run_all.sh` to exit `1`

**Comment by finnkauski** [comment]
Could you try now. Make sure to pass in the dates look up files for the date of reports you are looking at.

**Comment by finnkauski** [comment]
Reopening until the utility shell scripts are fixed

**Comment by finnkauski** [comment]
See `run_all.sh` for new usage of the script. Should work fine now.
