### ISSUE TITLE
Large trend lines cause misorder of CSV files

### ISSUE THREAD

**Issue by mshodge** [datasciencecampus/mobility-report-data-extractor#5]
**Describe the bug**
Sweden, and other reports, have graphs whose trend lines greatly exceed the +80% horizontal line. This causes strange behave in the order of which the individual graphs are saved and read. 

Need to isolate these cases and add conditions to prevent this. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mshodge** [comment]
Reordering seems to a pain. Solution: Cut PDFs in half (veriically, for pages 3 onwards) before processing. Will check.

**Comment by mshodge** [comment]
Above solution did give better results. But even then Csvs were misordered. 

Solution to test today: we know location of baselines stays constant for each graph, in a pattern, per page. So we can reorder paths, and attrs based on this knowledge.

**Comment by jwhendy** [comment]
Since this is closed, does that mean it's fixed now?
